# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.8'
        cache-dependency-path: go.sum

    - name: run unit test
      run: go test -v --cover ./...

    - name: run example
      run: go run example/example.go

    - name: run example with race
      env:
        REDIS_URL: CGO_ENABLED=1
      run: go run --race example/example.go
